# Generated by Django 5.0.2 on 2024-02-15 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="New_bookings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_name",
                    models.CharField(max_length=20, verbose_name=" Называние"),
                ),
                ("title_text", models.TextField(verbose_name="Краткое описание")),
                ("title_main_text", models.TextField(verbose_name="Описание")),
                (
                    "photo",
                    models.URLField(
                        blank=True, null=True, verbose_name="Главная Фотография"
                    ),
                ),
                (
                    "photo2",
                    models.URLField(blank=True, null=True, verbose_name="Фотография 2"),
                ),
                (
                    "photo3",
                    models.URLField(blank=True, null=True, verbose_name="Фотография 3"),
                ),
                (
                    "photo4",
                    models.URLField(blank=True, null=True, verbose_name="Фотография 4"),
                ),
                (
                    "photo5",
                    models.URLField(blank=True, null=True, verbose_name="Фотография 5"),
                ),
            ],
            options={
                "verbose_name": "Курорт",
                "verbose_name_plural": "Курорттар",
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Аты")),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Телефон номері"),
                ),
                ("booking_date", models.DateField(verbose_name="Брондау уақыты")),
                (
                    "resort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tours.new_bookings",
                        verbose_name="Курорт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Брондау",
                "verbose_name_plural": "Брондаулар",
            },
        ),
    ]
