# Generated by Django 4.1.7 on 2024-04-24 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='end_date',
            field=models.DateField(default=datetime.date(2024, 4, 24), verbose_name='Брондау уақыты аяқталады'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 4, 24), verbose_name='Брондау уақыты басталады'),
            preserve_default=False,
        ),
    ]
