# Generated by Django 4.1.7 on 2024-04-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_remove_booking_booking_date_booking_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_bookings',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
    ]
